import MarketingShell from '@/components/landing/MarketingShell';

export const metadata = { title: 'Privacy Policy — iTutor' };

const SECTIONS = [
  {
    title: 'Who We Are',
    body: 'iTutor is operated by Astronova Technologies Ltd., registered in Trinidad and Tobago. We are the data controller for personal information collected through the iTutor platform. If you have questions about how we handle your data, contact us at privacy@myitutor.com.',
  },
  {
    title: 'Information We Collect',
    body: 'We collect information you provide directly — such as your name, email address, and profile details — as well as information generated by your use of the platform, including booking history, session attendance, and payment records. We also collect device and usage data to improve platform performance and security.',
  },
  {
    title: 'How We Use Your Information',
    body: 'We use your information to operate and improve the platform, process bookings and payments, send booking confirmations and reminders, provide customer support, prevent fraud and abuse, and comply with legal obligations. We do not sell your personal data to third parties.',
  },
  {
    title: 'Sharing Your Information',
    body: 'We share limited information with third parties only where necessary: payment processors to handle transactions, video conferencing providers (Google, Zoom) to facilitate sessions, and cloud infrastructure providers to host the platform. All third parties are bound by data processing agreements. We may also share information with law enforcement where required by law.',
  },
  {
    title: 'Tutor and Student Profiles',
    body: 'Tutor profiles — including name, subject, biography, and ratings — are visible to all users of the platform. Student profiles are private by default and only shared with tutors you have booked or classes you have joined. You can control your profile visibility in your account settings.',
  },
  {
    title: 'Data Retention',
    body: 'We retain your account data for as long as your account is active. If you delete your account, we will delete your personal data within 30 days, except where we are required to retain it for legal or financial compliance reasons (such as payment records, which are retained for 7 years).',
  },
  {
    title: 'Cookies & Tracking',
    body: 'We use essential cookies to keep you logged in and maintain your session. We also use analytics tools to understand how users navigate the platform. You can manage cookie preferences in your browser settings. We do not use third-party advertising cookies.',
  },
  {
    title: 'Children\'s Privacy',
    body: 'Students under 18 may use iTutor with parental consent. We take additional care with the data of minors and do not use their data for marketing purposes. If you believe a child\'s data has been collected without consent, contact us immediately at privacy@myitutor.com.',
  },
  {
    title: 'Your Rights',
    body: 'You have the right to access, correct, or delete your personal data at any time. You can export your data or request account deletion from your account settings. For requests that cannot be handled through self-service, email privacy@myitutor.com and we will respond within 30 days.',
  },
  {
    title: 'Changes to This Policy',
    body: 'We may update this Privacy Policy from time to time. We will notify you of material changes via email at least 14 days before they take effect. The date at the top of this page always reflects the most recent update.',
  },
];

export default function PrivacyPage() {
  return (
    <MarketingShell>
      <section className="mx-auto max-w-6xl px-6 py-20">
        <h1 className="text-5xl font-bold tracking-tight sm:text-6xl">Privacy Policy</h1>
        <p className="mt-4 text-[#555555]">Data controller: Astronova Technologies Ltd.</p>
        <p className="mt-1 text-sm text-black/50">Last updated: June 2026 — placeholder until legal review</p>
      </section>

      <section className="mx-auto max-w-3xl px-6 pb-32">
        <div className="space-y-12">
          {SECTIONS.map((s, i) => (
            <div key={i}>
              <p className="text-xs uppercase tracking-wider text-black/40">Section {i + 1}</p>
              <h3 className="mt-2 text-2xl font-bold text-black">{s.title}</h3>
              <p className="mt-4 leading-relaxed text-[#555555]">{s.body}</p>
            </div>
          ))}
        </div>
        <div className="mt-16 rounded-2xl bg-[#F5F5F5] p-6 text-sm text-[#555555]">
          <p className="font-semibold text-black mb-2">Privacy enquiries</p>
          <p>Email <a href="mailto:privacy@myitutor.com" className="text-[#199356] hover:underline">privacy@myitutor.com</a> — we respond within 30 days.</p>
        </div>
      </section>
    </MarketingShell>
  );
}
