-- ============================================================
-- MIGRATION 169: PAYMENT CONTROL EXTENSION
-- ============================================================
-- Extends the payout hold system (migration 168) with:
--   - New hold reason values for group/session-specific events
--   - Group context columns on payout_cases
--   - payout_case_events: immutable audit trail
--   - Updated place_payout_hold RPC (group context params + events)
--   - Updated resolve_payout_case RPC (emits events)
--   - New reverse_payout_ledger_row helper RPC
-- ============================================================


-- ============================================================
-- 1. EXTEND hold_reason CHECKs
-- ============================================================
-- Drop existing auto-named CHECK constraints on hold_reason for
-- both tables (constraint names generated by Postgres convention)
-- then recreate with the full extended set of values.
-- ============================================================

DO $$
DECLARE v_con text;
BEGIN
  SELECT conname INTO v_con
  FROM pg_constraint
  WHERE conrelid = 'public.payout_ledger'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%hold_reason%'
  LIMIT 1;
  IF v_con IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.payout_ledger DROP CONSTRAINT %I', v_con);
  END IF;
END;
$$;

ALTER TABLE public.payout_ledger
  ADD CONSTRAINT payout_ledger_hold_reason_check
  CHECK (hold_reason IN (
    -- session disputes
    'student_reported_tutor_no_show',
    'refund_requested',
    'chargeback',
    'session_cancelled',
    'tutor_cancelled',
    -- group disputes
    'student_removed_from_group',
    'group_subscription_dispute',
    'class_access_issue',
    -- subscription
    'subscription_dispute',
    -- verdicts
    'tutor_no_show',
    'student_no_show',
    -- admin
    'manual_admin_hold',
    'system_inconsistency'
  ));

DO $$
DECLARE v_con text;
BEGIN
  SELECT conname INTO v_con
  FROM pg_constraint
  WHERE conrelid = 'public.payout_cases'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%hold_reason%'
  LIMIT 1;
  IF v_con IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.payout_cases DROP CONSTRAINT %I', v_con);
  END IF;
END;
$$;

ALTER TABLE public.payout_cases
  ADD CONSTRAINT payout_cases_hold_reason_check
  CHECK (hold_reason IN (
    'student_reported_tutor_no_show',
    'refund_requested',
    'chargeback',
    'session_cancelled',
    'tutor_cancelled',
    'student_removed_from_group',
    'group_subscription_dispute',
    'class_access_issue',
    'subscription_dispute',
    'tutor_no_show',
    'student_no_show',
    'manual_admin_hold',
    'system_inconsistency'
  ));


-- ============================================================
-- 2. ADD GROUP CONTEXT COLUMNS TO payout_cases
-- ============================================================

ALTER TABLE public.payout_cases
  ADD COLUMN IF NOT EXISTS student_id           uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS group_id             uuid REFERENCES public.groups(id)   ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS group_enrollment_id  uuid REFERENCES public.group_enrollments(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS group_removal_id     uuid REFERENCES public.group_removals(id)    ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS platform_fee_impact_ttd numeric(12,2);

CREATE INDEX IF NOT EXISTS payout_cases_group_id_idx          ON public.payout_cases (group_id);
CREATE INDEX IF NOT EXISTS payout_cases_student_id_idx        ON public.payout_cases (student_id);
CREATE INDEX IF NOT EXISTS payout_cases_group_removal_id_idx  ON public.payout_cases (group_removal_id);


-- ============================================================
-- 3. CREATE payout_case_events (immutable audit trail)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.payout_case_events (
  id            uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id       uuid         NOT NULL REFERENCES public.payout_cases(id) ON DELETE CASCADE,
  actor_id      uuid         REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_role    text         CHECK (actor_role IN ('admin','system','tutor','student')),
  event_type    text         NOT NULL CHECK (event_type IN (
    'case_opened',
    'hold_placed',
    'released_to_tutor',
    'refunded_to_student',
    'partial_split',
    'ledger_reversed',
    'case_closed',
    'case_dismissed',
    'note_added',
    'status_changed'
  )),
  before_status text,
  after_status  text,
  amount_ttd    numeric(12,2),
  notes         text,
  metadata      jsonb,
  created_at    timestamptz  NOT NULL DEFAULT now()
);

ALTER TABLE public.payout_case_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_all_payout_case_events"
  ON public.payout_case_events FOR ALL TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  ));

CREATE POLICY "tutor_read_own_payout_case_events"
  ON public.payout_case_events FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.payout_cases pc
    WHERE pc.id = payout_case_events.case_id
      AND pc.tutor_id = auth.uid()
  ));

GRANT ALL ON public.payout_case_events TO service_role;

CREATE INDEX IF NOT EXISTS payout_case_events_case_id_idx
  ON public.payout_case_events (case_id, created_at DESC);


-- ============================================================
-- 4. UPDATED place_payout_hold RPC
-- ============================================================
-- Extends the original with:
--   - Group context params (student_id, group_id, enrollment_id,
--     removal_id)
--   - Writes a payout_case_events row on success
-- The old 4-param signature is replaced; callers use named params
-- so adding new DEFAULT NULL params is non-breaking.
-- ============================================================

DROP FUNCTION IF EXISTS public.place_payout_hold(uuid, text, uuid, uuid);

CREATE OR REPLACE FUNCTION public.place_payout_hold(
  p_ledger_id           uuid,
  p_hold_reason         text,
  p_noshow_claim_id     uuid DEFAULT NULL,
  p_claimant_id         uuid DEFAULT NULL,
  p_student_id          uuid DEFAULT NULL,
  p_group_id            uuid DEFAULT NULL,
  p_group_enrollment_id uuid DEFAULT NULL,
  p_group_removal_id    uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ledger  record;
  v_case_id uuid;
BEGIN
  SELECT * INTO v_ledger
  FROM payout_ledger
  WHERE id = p_ledger_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'ledger_not_found: %', p_ledger_id;
  END IF;

  -- Idempotency: already held
  IF v_ledger.status = 'admin_hold' THEN
    SELECT id INTO v_case_id
    FROM payout_cases
    WHERE payout_ledger_id = p_ledger_id
      AND status IN ('open','under_review')
    LIMIT 1;
    RETURN jsonb_build_object(
      'ok', true, 'already_held', true,
      'case_id', v_case_id, 'ledger_id', p_ledger_id
    );
  END IF;

  IF v_ledger.status NOT IN ('owed','release_ready') THEN
    RAISE EXCEPTION 'ledger_not_holdable: status=%', v_ledger.status;
  END IF;

  -- Create payout_case with all available context
  INSERT INTO payout_cases (
    payout_ledger_id, session_id, subscription_payment_id,
    noshow_claim_id, claimant_id, tutor_id,
    student_id, group_id, group_enrollment_id, group_removal_id,
    hold_reason, status
  ) VALUES (
    p_ledger_id, v_ledger.session_id, v_ledger.subscription_payment_id,
    p_noshow_claim_id, COALESCE(p_claimant_id, p_student_id), v_ledger.tutor_id,
    p_student_id, p_group_id, p_group_enrollment_id, p_group_removal_id,
    p_hold_reason, 'open'
  )
  RETURNING id INTO v_case_id;

  -- Transition ledger → admin_hold
  UPDATE payout_ledger SET
    status      = 'admin_hold',
    hold_reason = p_hold_reason,
    case_id     = v_case_id,
    blocked_at  = now(),
    updated_at  = now()
  WHERE id = p_ledger_id;

  -- Decrement appropriate balance bucket
  IF v_ledger.status = 'owed' THEN
    UPDATE tutor_balances SET
      pending_ttd  = GREATEST(pending_ttd - v_ledger.amount_ttd, 0),
      last_updated = now()
    WHERE tutor_id = v_ledger.tutor_id;
  ELSIF v_ledger.status = 'release_ready' THEN
    UPDATE tutor_balances SET
      available_ttd = GREATEST(available_ttd - v_ledger.amount_ttd, 0),
      last_updated  = now()
    WHERE tutor_id = v_ledger.tutor_id;
  END IF;

  -- Audit event
  INSERT INTO payout_case_events (
    case_id, actor_role, event_type, before_status, after_status, amount_ttd, notes
  ) VALUES (
    v_case_id, 'system', 'hold_placed', v_ledger.status, 'admin_hold',
    v_ledger.amount_ttd, p_hold_reason
  );

  RETURN jsonb_build_object(
    'ok',          true,
    'already_held', false,
    'case_id',     v_case_id,
    'ledger_id',   p_ledger_id,
    'prev_status', v_ledger.status,
    'tutor_id',    v_ledger.tutor_id,
    'amount_ttd',  v_ledger.amount_ttd
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.place_payout_hold(uuid, text, uuid, uuid, uuid, uuid, uuid, uuid)
  TO service_role;


-- ============================================================
-- 5. UPDATED resolve_payout_case RPC (with event emission)
-- ============================================================

CREATE OR REPLACE FUNCTION public.resolve_payout_case(
  p_case_id            uuid,
  p_action             text,
  p_refund_amount_ttd  numeric DEFAULT NULL,
  p_release_amount_ttd numeric DEFAULT NULL,
  p_admin_id           uuid    DEFAULT NULL,
  p_admin_notes        text    DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_case        record;
  v_ledger      record;
  v_has_ledger  boolean := false;
  v_new_status  text;
  v_event_type  text;
  v_now         timestamptz := now();
BEGIN
  SELECT * INTO v_case
  FROM payout_cases
  WHERE id = p_case_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'case_not_found: %', p_case_id;
  END IF;

  IF v_case.status NOT IN ('open','under_review') THEN
    RAISE EXCEPTION 'case_already_resolved: status=%', v_case.status;
  END IF;

  IF p_action NOT IN ('release_to_tutor','refund_student','partial_refund') THEN
    RAISE EXCEPTION 'invalid_action: %', p_action;
  END IF;

  -- Load ledger row if present
  IF v_case.payout_ledger_id IS NOT NULL THEN
    SELECT * INTO v_ledger
    FROM payout_ledger
    WHERE id = v_case.payout_ledger_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'ledger_not_found: %', v_case.payout_ledger_id;
    END IF;

    IF v_ledger.status != 'admin_hold' THEN
      RAISE EXCEPTION 'ledger_not_in_admin_hold: status=%', v_ledger.status;
    END IF;

    v_has_ledger := true;
  END IF;

  -- ── Ledger-exists paths ──────────────────────────────────────────
  IF v_has_ledger THEN

    IF p_action = 'release_to_tutor' THEN
      UPDATE payout_ledger SET
        status      = 'owed',
        hold_reason = NULL,
        case_id     = NULL,
        blocked_at  = NULL,
        updated_at  = v_now
      WHERE id = v_ledger.id;

      INSERT INTO tutor_balances (tutor_id, pending_ttd, available_ttd, last_updated)
      VALUES (v_ledger.tutor_id, v_ledger.amount_ttd, 0, v_now)
      ON CONFLICT (tutor_id) DO UPDATE SET
        pending_ttd  = tutor_balances.pending_ttd + EXCLUDED.pending_ttd,
        last_updated = v_now;

      v_new_status := 'resolved_release_to_tutor';
      v_event_type := 'released_to_tutor';

    ELSIF p_action = 'refund_student' THEN
      -- admin_hold → reversed; no balance change (decremented at hold time)
      UPDATE payout_ledger SET
        status     = 'reversed',
        updated_at = v_now
      WHERE id = v_ledger.id;

      v_new_status := 'resolved_refund_student';
      v_event_type := 'refunded_to_student';

    ELSIF p_action = 'partial_refund' THEN
      IF p_release_amount_ttd IS NULL OR p_release_amount_ttd < 0 THEN
        RAISE EXCEPTION 'invalid_release_amount_ttd: %', p_release_amount_ttd;
      END IF;

      -- admin_hold → owed with reduced amount; restore only release portion
      UPDATE payout_ledger SET
        amount_ttd  = p_release_amount_ttd,
        status      = 'owed',
        hold_reason = NULL,
        case_id     = NULL,
        blocked_at  = NULL,
        updated_at  = v_now
      WHERE id = v_ledger.id;

      IF p_release_amount_ttd > 0 THEN
        INSERT INTO tutor_balances (tutor_id, pending_ttd, available_ttd, last_updated)
        VALUES (v_ledger.tutor_id, p_release_amount_ttd, 0, v_now)
        ON CONFLICT (tutor_id) DO UPDATE SET
          pending_ttd  = tutor_balances.pending_ttd + EXCLUDED.pending_ttd,
          last_updated = v_now;
      END IF;

      v_new_status := 'resolved_partial_refund';
      v_event_type := 'partial_split';
    END IF;

  -- ── Null-ledger paths ────────────────────────────────────────────
  ELSE

    IF p_action = 'release_to_tutor' THEN
      -- Dismiss: future ledger creation proceeds as normal owed
      UPDATE payout_cases SET
        status      = 'dismissed',
        admin_id    = p_admin_id,
        admin_notes = p_admin_notes,
        resolved_at = v_now,
        updated_at  = v_now
      WHERE id = p_case_id;

      INSERT INTO payout_case_events (
        case_id, actor_id, actor_role, event_type, before_status, after_status, notes
      ) VALUES (
        p_case_id, p_admin_id, 'admin', 'case_dismissed',
        v_case.status, 'dismissed', p_admin_notes
      );

      RETURN jsonb_build_object(
        'ok', true, 'action', 'dismissed',
        'case_id', p_case_id, 'no_ledger', true
      );

    ELSIF p_action = 'refund_student' THEN
      UPDATE payout_cases SET
        status      = 'resolved_refund_student',
        admin_id    = p_admin_id,
        admin_notes = p_admin_notes,
        resolved_at = v_now,
        updated_at  = v_now
      WHERE id = p_case_id;

      INSERT INTO payout_case_events (
        case_id, actor_id, actor_role, event_type, before_status, after_status, notes
      ) VALUES (
        p_case_id, p_admin_id, 'admin', 'refunded_to_student',
        v_case.status, 'resolved_refund_student', p_admin_notes
      );

      RETURN jsonb_build_object(
        'ok', true, 'action', 'resolved_refund_student',
        'case_id', p_case_id, 'no_ledger', true
      );

    ELSIF p_action = 'partial_refund' THEN
      RAISE EXCEPTION 'partial_refund_requires_ledger';
    END IF;
  END IF;

  -- Update payout_case (ledger-exists paths)
  UPDATE payout_cases SET
    status             = v_new_status,
    refund_amount_ttd  = p_refund_amount_ttd,
    release_amount_ttd = p_release_amount_ttd,
    admin_id           = p_admin_id,
    admin_notes        = p_admin_notes,
    resolved_at        = v_now,
    updated_at         = v_now
  WHERE id = p_case_id;

  -- Audit event
  INSERT INTO payout_case_events (
    case_id, actor_id, actor_role, event_type, before_status, after_status,
    amount_ttd, notes
  ) VALUES (
    p_case_id, p_admin_id, 'admin', v_event_type,
    v_case.status, v_new_status,
    CASE p_action
      WHEN 'release_to_tutor' THEN v_ledger.amount_ttd
      WHEN 'refund_student'   THEN v_ledger.amount_ttd
      WHEN 'partial_refund'   THEN p_refund_amount_ttd
    END,
    p_admin_notes
  );

  RETURN jsonb_build_object(
    'ok',        true,
    'action',    p_action,
    'case_id',   p_case_id,
    'ledger_id', v_case.payout_ledger_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.resolve_payout_case(uuid, text, numeric, numeric, uuid, text)
  TO service_role;


-- ============================================================
-- 6. NEW reverse_payout_ledger_row HELPER RPC
-- ============================================================
-- Called from TypeScript when a refund is issued through a path
-- that does not go through apply_refund_side_effects (e.g. the
-- group member removal route). Atomically:
--   - Sets the ledger row to reversed
--   - Decrements the appropriate tutor_balances bucket
--     (no balance change if ledger was already admin_hold since
--      the balance was decremented at hold time)
--   - Closes any open payout_case linked to this ledger
--   - Emits a payout_case_events row
-- Idempotent: safe to call if ledger is already reversed.
-- ============================================================

CREATE OR REPLACE FUNCTION public.reverse_payout_ledger_row(
  p_ledger_id  uuid,
  p_removal_id uuid DEFAULT NULL,
  p_admin_id   uuid DEFAULT NULL,
  p_notes      text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ledger  record;
  v_case    record;
  v_now     timestamptz := now();
BEGIN
  SELECT * INTO v_ledger
  FROM payout_ledger
  WHERE id = p_ledger_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'ledger_not_found: %', p_ledger_id;
  END IF;

  -- Idempotent: already reversed
  IF v_ledger.status = 'reversed' THEN
    RETURN jsonb_build_object(
      'ok', true, 'already_reversed', true, 'ledger_id', p_ledger_id
    );
  END IF;

  IF v_ledger.status = 'released' THEN
    RAISE EXCEPTION 'ledger_already_released: cannot reverse a released payout ledger row';
  END IF;

  -- Transition ledger → reversed
  UPDATE payout_ledger SET
    status     = 'reversed',
    updated_at = v_now
  WHERE id = p_ledger_id;

  -- Decrement balance bucket (only for rows that were in normal flow;
  -- admin_hold rows had their balance decremented at hold time)
  IF v_ledger.status = 'owed' THEN
    UPDATE tutor_balances SET
      pending_ttd  = GREATEST(pending_ttd - v_ledger.amount_ttd, 0),
      last_updated = v_now
    WHERE tutor_id = v_ledger.tutor_id;

  ELSIF v_ledger.status = 'release_ready' THEN
    UPDATE tutor_balances SET
      available_ttd = GREATEST(available_ttd - v_ledger.amount_ttd, 0),
      last_updated  = v_now
    WHERE tutor_id = v_ledger.tutor_id;

  -- admin_hold: no balance adjustment needed
  END IF;

  -- Find and close any open payout_case linked to this ledger
  SELECT * INTO v_case
  FROM payout_cases
  WHERE payout_ledger_id = p_ledger_id
    AND status IN ('open','under_review')
  FOR UPDATE
  LIMIT 1;

  IF FOUND THEN
    UPDATE payout_cases SET
      status      = 'closed',
      admin_id    = p_admin_id,
      admin_notes = COALESCE(p_notes, 'Closed: payout reversed via group removal refund'),
      resolved_at = v_now,
      updated_at  = v_now
    WHERE id = v_case.id;

    INSERT INTO payout_case_events (
      case_id, actor_id, actor_role, event_type, before_status, after_status,
      amount_ttd, notes, metadata
    ) VALUES (
      v_case.id, p_admin_id, 'system', 'ledger_reversed',
      v_case.status, 'closed', v_ledger.amount_ttd, p_notes,
      CASE WHEN p_removal_id IS NOT NULL
        THEN jsonb_build_object('group_removal_id', p_removal_id)
        ELSE NULL
      END
    );
  END IF;

  RETURN jsonb_build_object(
    'ok',            true,
    'already_reversed', false,
    'ledger_id',     p_ledger_id,
    'prev_status',   v_ledger.status,
    'tutor_id',      v_ledger.tutor_id,
    'amount_ttd',    v_ledger.amount_ttd,
    'case_id',       v_case.id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.reverse_payout_ledger_row(uuid, uuid, uuid, text)
  TO service_role;


-- ============================================================
-- VERIFICATION
-- ============================================================

DO $$
BEGIN
  ASSERT to_regclass('public.payout_case_events') IS NOT NULL,
    'payout_case_events table missing';

  ASSERT (
    SELECT COUNT(*) FROM information_schema.columns
    WHERE table_name = 'payout_cases'
      AND column_name IN ('student_id','group_id','group_enrollment_id',
                          'group_removal_id','platform_fee_impact_ttd')
  ) = 5, 'payout_cases new columns missing';

  ASSERT (
    SELECT COUNT(*) FROM pg_proc
    WHERE proname = 'reverse_payout_ledger_row'
  ) >= 1, 'reverse_payout_ledger_row RPC missing';

  RAISE NOTICE 'Migration 169 verified successfully.';
END;
$$;
